name: geomosaic_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-irkernel
  - r-tidyverse
  - r-vegan
  - r-pheatmap
  - r-stringr
  - r-circlize
  - r-igraph
  - r-png       
  - r-data.table
  - r-fs   
  - r-ggrepel
  - r-svglite
  - r-patchwork
  - bioconductor-complexheatmap
  - bioconductor-phyloseq
  - bioconductor-biostrings
  - bioconductor-xvector    
  - bioconductor-microbiome
  - jupyter_client
  - jupyter_core